#!/bin/bash

userid=$(id -u)
Timestamp=$(date +%F-%H-%M-%S)
Script_Name=$(echo $0 | cut -d "." -f1)
Logfile=/tmp/$Script_Name-$Timestamp.log
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

validate() {
    if [ $1 -ne 0 ]; then 
        echo -e "$2...$R Failure $N"
    else
        echo -e "$2...$G Success $N"
    fi 
}

if [ $userid -ne 0 ]; then
    echo "Please run the script with root access"
    exit 1
else 
    echo "You are super user"
fi

# Step 1: Install Node.js 20
dnf module disable nodejs -y &>>$Logfile
validate $? "Disabling default Node.js module"

dnf module enable nodejs:20 -y &>>$Logfile
validate $? "Enabling Node.js 20 module"

dnf install nodejs -y &>>$Logfile
validate $? "Installing Node.js"

# Step 2: Create user if not exists
id expense &>>$Logfile
if [ $? -ne 0 ]; then
    useradd expense &>>$Logfile
    validate $? "Creating expense user"
else 
    echo -e "Expense user already created...$Y Skipping $N"
fi 

# Step 3: Create /app directory
mkdir -p /app &>>$Logfile
validate $? "Creating app directory"

# Step 4: Download and extract backend code
curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip &>>$Logfile
if [ $? -eq 0 ]; then
  validate 0 "Downloading backend code"

  rm -rf /app/* &>>$Logfile
  validate $? "Cleaning old app contents"

  unzip /tmp/backend.zip -d /app &>>$Logfile
  validate $? "Extracting backend code"
else
  validate 1 "Downloading backend code"
  echo -e "$R Skipping cleanup and unzip because download failed $N"
  exit 1
fi

# Step 5: Install nodejs dependencies
cd /app
npm install &>>$Logfile
validate $? "Installing Node.js dependencies"

# Step 6: Setup systemd service
mysql_root_password=ExpenseApp@1

cp /home/ec2-user/expense-shell/backend /etc/systemd/system/backend &>>$Logfile
validate $? "Copied backend service file"

systemctl daemon-reload &>>$Logfile
validate $? "Systemd daemon reload"

systemctl start backend &>>$Logfile
validate $? "Starting backend service"

systemctl enable backend &>>$Logfile
validate $? "Enabling backend service"

# Step 7: Install MySQL client
dnf install mysql -y &>>$Logfile
validate $? "Installing MySQL client"

# Step 8: Load DB schema
mysql -h 172.31.91.208 -uroot -p${mysql_root_password} < /app/schema/backend.sql &>>$Logfile
validate $? "Loading schema"

# Step 9: Restart backend
systemctl restart backend &>>$Logfile
validate $? "Restarting backend service"
